In [ ]:
print("hjk")

hjk

In [ ]:
import pandas as pd

In [ ]:
#Series(1 daimensional)(array is capable)(data types: int,str,float,python object)
#data : (actual vale stores [1,2,3,4])
#index:(assoaicted with each value)

In [ ]:
data =[1,2,3,4]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s=pd.Series(data,index=['a','b','c','d'])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s=pd.Series(data,index=[1,2,3,4])
print(s)

1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
s = pd.Series(data=[1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#with dict
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
print(s2)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
#Accessing elements series
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:6])

set[slice(None, 6, None)]

In [ ]:
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:-6])

set[slice(None, -6, None)]

In [ ]:
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[6:])

set[slice(6, None, None)]

In [ ]:
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[-6:])

set[slice(-6, None, None)]

In [ ]:
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[-3:])
print(set[7:8])
print(set[:6])

set[slice(-3, None, None)]
set[slice(7, 8, None)]
set[slice(None, 6, None)]

In [ ]:
#updating
import pandas as pd
data = ['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:6])
ser['z']=10
print(ser)

set[slice(None, 6, None)]
0     g
1     r
2     r
3     h
4     k
5     u
6     o
7     p
z    10
dtype: object

In [ ]:
#adding

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(s1+s2)

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [ ]:
#drop (it was drop statically)
s1 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s1.drop('a'))

b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#drop (it was dynamically drop)
marks = pd.Series([78,85,92,76,88],index=[101,102,103,104,105])
print(marks)
print(marks[103])
marks[104] = 75
print(marks)
marks=marks.drop(103)
print(marks)
marks[106]=90
print(marks)

101    78
102    85
103    92
104    76
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
102    85
104    75
105    88
dtype: int64
101    78
102    85
104    75
105    88
106    90
dtype: int64

In [ ]:
#product prices
price = pd.Series([500,750,1200,900,1500],index=[101,102,103,104,105])
price_value = price[103]
print(price_value)
price[103]=400
print(price)
price=price.drop(102)
print(price)
price[106]=550
print(price)
print(price[:3])

1200
101     500
102     750
103     400
104     900
105    1500
dtype: int64
101     500
103     400
104     900
105    1500
dtype: int64
101     500
103     400
104     900
105    1500
106     550
dtype: int64
101    500
103    400
104    900
dtype: int64

In [ ]:
#employeee salaries
salary = pd.Series([50000,75000,120000,90000,150000],index=[101,102,103,104,105])
salary_value = salary[103]
print(salary_value)
salary[103]=40000
print(salary)
salary=salary.drop(102)
print(salary)
salary[106]=55000
print(salary)
print(salary[:3])

120000
101     50000
102     75000
103     40000
104     90000
105    150000
dtype: int64
101     50000
103     40000
104     90000
105    150000
dtype: int64
101     50000
103     40000
104     90000
105    150000
106     55000
dtype: int64
101    50000
103    40000
104    90000
dtype: int64

In [ ]:
#daily Tempreature
import pandas as pd
temp = pd.Series(
    [31, 32, 34, 33, 35, 36, 34],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])
print(temp)
print(temp.loc["Monday":"Wednesday"])
temp["Thursday"] = 32
print(temp)
temp = temp.drop("Saturday")
print(temp)

Monday       31
Tuesday      32
Wednesday    34
Thursday     33
Friday       35
Saturday     36
Sunday       34
dtype: int64
Monday       31
Tuesday      32
Wednesday    34
dtype: int64
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Saturday     36
Sunday       34
dtype: int64
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Sunday       34
dtype: int64

In [ ]:
#Bank account balance
import pandas as pd
balance = pd.Series([25000, 45000, 32000, 18000, 60000], index=["A101", "A102", "A103", "A104", "A105"])
print(balance)
print(balance["A103"])
balance['A104'] = 25000
balance = balance.drop("A102")
print(balance)
balance['A106'] = 48000

A101    25000
A102    45000
A103    32000
A104    18000
A105    60000
dtype: int64
32000
A101    25000
A103    32000
A104    25000
A105    60000
dtype: int64

#cleaning data : we use (drop)
#pd series we usec (pd.series, index, dictonary)

#Data Frames: (rows and columns)
syntax: (pd.DataFrame)
1. data = [["ravi",22,3000],["sai",23,6900],["poori",67,8099]]
 df = pd.DataFrame(data)
 print(df)

In [ ]:
#data Frames creation
# use list
import pandas as pd
data = [["Sai",22,30000],["Raja",24,50000],["poori",21,25000]]
df = pd.DataFrame(data)
print(df)

       0   1      2
0    Sai  22  30000
1   Raja  24  50000
2  poori  21  25000

#data frame tuple
import pandas as pd
data = (["Sai",22,30000],["Raja",24,50000],["poori",21,25000])
df = pd.DataFrame(data)
print(df)

In [ ]:
#use dictonaryd
import pandas as pd
data = [["Sai",22,30000],["Raja",24,50000],["poori",21,25000]]
df = pd.DataFrame(data,columns=["Name","Age","Salary"])
print(df)

    Name  Age  Salary
0    Sai   22   30000
1   Raja   24   50000
2  poori   21   25000

In [ ]:
#Create data frame
#sales and profit of every month first 6 month of the year.
import pandas as pd
sales = [["jan",200,100],["feb",100,200],["mar",100,300],["may",190,569],["june",809,780],["july",780,2000]]
df=pd.DataFrame(sales,columns=["month","sales","profit"])
print(df)

  month  sales  profit
0   jan    200     100
1   feb    100     200
2   mar    100     300
3   may    190     569
4  june    809     780
5  july    780    2000

In [ ]:
#use set
import pandas as pd
my_set = {1,2,3,4,5}
df = pd.DataFrame(list(my_set),columns=["numbers"])
print(df)

   numbers
0        1
1        2
2        3
3        4
4        5

In [ ]:
#single series
import pandas as pd
s = pd.Series([1,2,3,4,5],name="numbers")
df = s.to_frame()
print(df)

   numbers
0        1
1        2
2        3
3        4
4        5

In [ ]:
#Multipple Series
import pandas as pd
s2 = pd.Series([9,5,7,8])
s3 = pd.Series([1,2,3,4])
d = {
    "marks-A" :s,
     "marks-B" :s2,
     "marks-c" :s3
 }
df = pd.DataFrame(d)
print(df)

   marks-A  marks-B  marks-c
0        1      9.0      1.0
1        2      5.0      2.0
2        3      7.0      3.0
3        4      8.0      4.0
4        5      NaN      NaN

In [ ]:
#rename columns
import pandas as pd
s = pd.Series([1,2,3,4,5],name="numbers")
df = s.to_frame()
df.columns = ["digiths"]
print(df)

   digiths
0        1
1        2
2        3
3        4
4        5

In [ ]:
#Rename columns
import pandas as pd
s2 = pd.Series([9,5,7,8])
s3 = pd.Series([1,2,3,4])
d = {
    "marks-A" :s,
     "marks-B" :s2,
     "marks-c" :s3
 }
df = pd.DataFrame(d)
df.columns = ["A","B","C"]
print(df)

   A    B    C
0  1  9.0  1.0
1  2  5.0  2.0
2  3  7.0  3.0
3  4  8.0  4.0
4  5  NaN  NaN

In [ ]:
#Rename the existing columns (inplce true (change permantely)
import pandas as pd
df = pd.DataFrame({
    "A":[1,2,3,4],
    "B":[5,6,7,8],
    "C":[9,10,11,12]
})
print(df)

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [ ]:
df.rename(columns={"A":"a","B":"b","C":"c"},inplace=True)
print(df)

   a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [ ]:
#top rows (head)
#bottom rows (tail)
#length
#shape
#values
#index
import pandas as pd
s2 = pd.Series([9,5,7,8,7,8,9,6,7,7,8,9])
s3 = pd.Series([1,2,3,4,7,6,5,5,4,5,6,7])
print(s2.head(5))
print(s3.tail(5))
print(len)
print(df.shape)
print(df.index)
print(df.values)

0    9
1    5
2    7
3    8
4    7
dtype: int64
7     5
8     4
9     5
10    6
11    7
dtype: int64
<built-in function len>
(4, 3)
RangeIndex(start=0, stop=4, step=1)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

In [ ]:
#1.create list
import pandas as pd
employees = (["sai",23,"vizag",50000],["raja",56,"hyd",80000],["poori",67,"beng",87000],["sneha",45,"africa",670000],["bhagi",23,"kol",98000])
df = pd.DataFrame(employees,columns=["name","age","city","salary"])
print(df)

    name  age    city  salary
0    sai   23   vizag   50000
1   raja   56     hyd   80000
2  poori   67    beng   87000
3  sneha   45  africa  670000
4  bhagi   23     kol   98000

In [ ]:
#craete dic
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Keyboard", "Mouse", "Headphones"],
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Accessories"],
    "Price": [55000, 25000, 1500, 800, 2000],
    "Quantity": [5, 10, 15, 20, 8]
}

df = pd.DataFrame(data)

print(df)

      Product     Category  Price  Quantity
0      Laptop  Electronics  55000         5
1      Mobile  Electronics  25000        10
2    Keyboard  Accessories   1500        15
3       Mouse  Accessories    800        20
4  Headphones  Accessories   2000         8

In [ ]:
#Create a DataFrame using a List of Dictionaries
import pandas as pd
data = [
    {"Student_ID": 101, "Name": "Rahul", "Course": "Python", "Marks": 85},
    {"Student_ID": 102, "Name": "Priya", "Course": "Data Science", "Marks": 90},
    {"Student_ID": 103, "Name": "Arun", "Course": "Python", "Marks": 78},
    {"Student_ID": 104, "Name": "Sneha", "Course": "Data Analytics", "Marks": 88},
    {"Student_ID": 105, "Name": "Kiran", "Course": "Python", "Marks": 82}
]
df = pd.DataFrame(data)
print(df)

   Student_ID   Name          Course  Marks
0         101  Rahul          Python     85
1         102  Priya    Data Science     90
2         103   Arun          Python     78
3         104  Sneha  Data Analytics     88
4         105  Kiran          Python     82

In [ ]:
#tuple
import pandas as pd
data = [
    (101, "HR", 3),
    (102, "IT", 5),
    (103, "Finance", 2),
    (104, "Marketing", 4),
    (105, "IT", 6)
]
df = pd.DataFrame(
    data,
    columns=["Employee_ID", "Department", "Experience"]
)
print(df)

   Employee_ID Department  Experience
0          101         HR           3
1          102         IT           5
2          103    Finance           2
3          104  Marketing           4
4          105         IT           6

In [ ]:
#panda series
import pandas as pd
name = pd.Series(["Rahul", "Priya", "Arun", "Sneha", "Kiran"])
age = pd.Series([22, 23, 24, 21, 25])
city = pd.Series(["Hyderabad", "Vizag", "Chennai", "Bangalore", "Vijayawada"])
df = pd.DataFrame({
    "Name": name,
    "Age": age,
    "City": city
})
print(df)

    Name  Age        City
0  Rahul   22   Hyderabad
1  Priya   23       Vizag
2   Arun   24     Chennai
3  Sneha   21   Bangalore
4  Kiran   25  Vijayawada

In [ ]:
#Seleting and filtering
#ioc : (integer)
#iloc : interger based

In [ ]:
#create data frame
import pandas as pd
data = {
    "Name": ["Rahul", "Priya", "Arun", "Sneha", "Kiran","sai","lokesh","raja"],
    "Age": [22, 23, 24, 21, 25, 67, 89, 56],
    "City": ["Hyderabad", "Vizag", "Chennai", "Bangalore", "Vijayawada","kolkata","mumbai","goa"],
    "Salary": [50000, 60000, 70000, 80000, 90000, 800000, 7000000, 760000 ]
}
df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age        City   Salary
101   Rahul   22   Hyderabad    50000
102   Priya   23       Vizag    60000
103    Arun   24     Chennai    70000
104   Sneha   21   Bangalore    80000
105   Kiran   25  Vijayawada    90000
106     sai   67     kolkata   800000
107  lokesh   89      mumbai  7000000
108    raja   56         goa   760000

In [ ]:
#bottom values
print(df.tail())

     Name  Age        City   Salary
3   Sneha   21   Bangalore    80000
4   Kiran   25  Vijayawada    90000
5     sai   67     kolkata   800000
6  lokesh   89      mumbai  7000000
7    raja   56         goa   760000

In [ ]:
#top values
print(df.head())

    Name  Age        City  Salary
0  Rahul   22   Hyderabad   50000
1  Priya   23       Vizag   60000
2   Arun   24     Chennai   70000
3  Sneha   21   Bangalore   80000
4  Kiran   25  Vijayawada   90000

In [ ]:
#dataframe discription
print(df.info()m)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes
None

In [ ]:
#show values
print(df.describe())

             Age        Salary
count   8.000000  8.000000e+00
mean   40.875000  1.113750e+06
std    26.281104  2.399988e+06
min    21.000000  5.000000e+04
25%    22.750000  6.750000e+04
50%    24.500000  8.500000e+04
75%    58.750000  7.700000e+05
max    89.000000  7.000000e+06

In [ ]:
#values length
print(len(df))

8

In [ ]:
#show columns and rows
print(df.shape)

(8, 4)

In [ ]:
#show values
print(df.index)

RangeIndex(start=0, stop=8, step=1)

In [ ]:
#name and age
print(df[['Name', 'Age']])

     Name  Age
0   Rahul   22
1   Priya   23
2    Arun   24
3   Sneha   21
4   Kiran   25
5     sai   67
6  lokesh   89
7    raja   56

In [ ]:
print(df[["City", "Salary"]])

         City   Salary
0   Hyderabad    50000
1       Vizag    60000
2     Chennai    70000
3   Bangalore    80000
4  Vijayawada    90000
5     kolkata   800000
6      mumbai  7000000
7         goa   760000

In [ ]:
print(df.iloc)

<pandas.core.indexing._iLocIndexer object at 0x7ac91bbd7700>

In [ ]:
print(df.iloc[0:3])

    Name  Age       City  Salary
0  Rahul   22  Hyderabad   50000
1  Priya   23      Vizag   60000
2   Arun   24    Chennai   70000

In [ ]:
print(df.iloc[2])

Name         Arun
Age            24
City      Chennai
Salary      70000
Name: 2, dtype: object

In [ ]:
print(df.loc[102])

Name      Priya
Age          23
City      Vizag
Salary    60000
Name: 102, dtype: object

In [ ]:
print(df.loc[108])

Name        raja
Age           56
City         goa
Salary    760000
Name: 108, dtype: object

In [ ]:
print(df.loc[102:108])

       Name  Age        City   Salary
102   Priya   23       Vizag    60000
103    Arun   24     Chennai    70000
104   Sneha   21   Bangalore    80000
105   Kiran   25  Vijayawada    90000
106     sai   67     kolkata   800000
107  lokesh   89      mumbai  7000000
108    raja   56         goa   760000

In [ ]:
print(df[df["Salary"] > 45000])

       Name  Age        City   Salary
101   Rahul   22   Hyderabad    50000
102   Priya   23       Vizag    60000
103    Arun   24     Chennai    70000
104   Sneha   21   Bangalore    80000
105   Kiran   25  Vijayawada    90000
106     sai   67     kolkata   800000
107  lokesh   89      mumbai  7000000
108    raja   56         goa   760000

In [ ]:
df['Salary'] > 35000

101    True
102    True
103    True
104    True
105    True
106    True
107    True
108    True
Name: Salary, dtype: bool

In [ ]:
df['Salary'] < 45000

101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
Name: Salary, dtype: bool

In [ ]:
data={
      "student_id":[101,102,103,104,105,106,107,108,109,110],
      "name":['Aarav','Priya','Rahul','Sneha','Arjun',
              'Divya','Kiran','Ananya','Rohit','Meena'],
      "age":[20,21,19,22,20,21,23,19,22,20],
      "course":['python','power bi','python','excel','python',
                'power bi','excel','python','power bi','excel'],
      "marks":[85,78,92,67,88,74,81,95,69,90],
      "attendace":[92,85,96,78,89,82,91,98,75,94],
      "city":['Hyderabad','Chennai','Bangalore','Hyderbad','Pune',
              'Chennai','Hyderbad','Bangalore','Pune','Hyderbad']}

df=pd.DataFrame(data)
print(df)

   student_id    name  age    course  marks  attendace       city
0         101   Aarav   20    python     85         92  Hyderabad
1         102   Priya   21  power bi     78         85    Chennai
2         103   Rahul   19    python     92         96  Bangalore
3         104   Sneha   22     excel     67         78   Hyderbad
4         105   Arjun   20    python     88         89       Pune
5         106   Divya   21  power bi     74         82    Chennai
6         107   Kiran   23     excel     81         91   Hyderbad
7         108  Ananya   19    python     95         98  Bangalore
8         109   Rohit   22  power bi     69         75       Pune
9         110   Meena   20     excel     90         94   Hyderbad

In [ ]:
#viewing data
print(df.head())

   student_id   name  age    course  marks  attendace       city
0         101  Aarav   20    python     85         92  Hyderabad
1         102  Priya   21  power bi     78         85    Chennai
2         103  Rahul   19    python     92         96  Bangalore
3         104  Sneha   22     excel     67         78   Hyderbad
4         105  Arjun   20    python     88         89       Pune

In [ ]:
print(df.tail())

   student_id    name  age    course  marks  attendace       city
5         106   Divya   21  power bi     74         82    Chennai
6         107   Kiran   23     excel     81         91   Hyderbad
7         108  Ananya   19    python     95         98  Bangalore
8         109   Rohit   22  power bi     69         75       Pune
9         110   Meena   20     excel     90         94   Hyderbad

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   course      10 non-null     object
 4   marks       10 non-null     int64
 5   attendace   10 non-null     int64
 6   city        10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [ ]:
df[["name"]]

     name
0   Aarav
1   Priya
2   Rahul
3   Sneha
4   Arjun
5   Divya
6   Kiran
7  Ananya
8   Rohit
9   Meena

In [ ]:
df[["name","course","marks"]]

     name    course  marks
0   Aarav    python     85
1   Priya  power bi     78
2   Rahul    python     92
3   Sneha     excel     67
4   Arjun    python     88
5   Divya  power bi     74
6   Kiran     excel     81
7  Ananya    python     95
8   Rohit  power bi     69
9   Meena     excel     90

In [ ]:
print(df.loc[:,["student_id", "age", "attendace", "city"]])

   student_id  age  attendace       city
0         101   20         92  Hyderabad
1         102   21         85    Chennai
2         103   19         96  Bangalore
3         104   22         78   Hyderbad
4         105   20         89       Pune
5         106   21         82    Chennai
6         107   23         91   Hyderbad
7         108   19         98  Bangalore
8         109   22         75       Pune
9         110   20         94   Hyderbad

In [ ]:
df.loc[2:6]

   student_id   name  age    course  marks  attendace       city
2         103  Rahul   19    python     92         96  Bangalore
3         104  Sneha   22     excel     67         78   Hyderbad
4         105  Arjun   20    python     88         89       Pune
5         106  Divya   21  power bi     74         82    Chennai
6         107  Kiran   23     excel     81         91   Hyderbad

In [ ]:
df[["name", "city", "marks"]]

     name       city  marks
0   Aarav  Hyderabad     85
1   Priya    Chennai     78
2   Rahul  Bangalore     92
3   Sneha   Hyderbad     67
4   Arjun       Pune     88
5   Divya    Chennai     74
6   Kiran   Hyderbad     81
7  Ananya  Bangalore     95
8   Rohit       Pune     69
9   Meena   Hyderbad     90

In [ ]:
#10
df.loc[7,["name","marks","city"]]

name        Ananya
marks           95
city     Bangalore
Name: 7, dtype: object

In [ ]:
#11
df.iloc[:4]

   student_id   name  age    course  marks  attendace       city
0         101  Aarav   20    python     85         92  Hyderabad
1         102  Priya   21  power bi     78         85    Chennai
2         103  Rahul   19    python     92         96  Bangalore
3         104  Sneha   22     excel     67         78   Hyderbad

In [ ]:
#11
df.iloc[:5]

   student_id   name  age    course  marks  attendace       city
0         101  Aarav   20    python     85         92  Hyderabad
1         102  Priya   21  power bi     78         85    Chennai
2         103  Rahul   19    python     92         96  Bangalore
3         104  Sneha   22     excel     67         78   Hyderbad
4         105  Arjun   20    python     88         89       Pune

In [ ]:
df.iloc[0:4,0:5]

   student_id   name  age    course  marks
0         101  Aarav   20    python     85
1         102  Priya   21  power bi     78
2         103  Rahul   19    python     92
3         104  Sneha   22     excel     67

In [ ]:
#12
df[["name", "course", "marks"]].iloc[2:6]

    name    course  marks
2  Rahul    python     92
3  Sneha     excel     67
4  Arjun    python     88
5  Divya  power bi     74

In [ ]:
#13
df.iloc[:-1]

   student_id    name  age    course  marks  attendace       city
0         101   Aarav   20    python     85         92  Hyderabad
1         102   Priya   21  power bi     78         85    Chennai
2         103   Rahul   19    python     92         96  Bangalore
3         104   Sneha   22     excel     67         78   Hyderbad
4         105   Arjun   20    python     88         89       Pune
5         106   Divya   21  power bi     74         82    Chennai
6         107   Kiran   23     excel     81         91   Hyderbad
7         108  Ananya   19    python     95         98  Bangalore
8         109   Rohit   22  power bi     69         75       Pune

In [ ]:
#14
df[df['marks']>80]

   student_id    name  age  course  marks  attendace       city
0         101   Aarav   20  python     85         92  Hyderabad
2         103   Rahul   19  python     92         96  Bangalore
4         105   Arjun   20  python     88         89       Pune
6         107   Kiran   23   excel     81         91   Hyderbad
7         108  Ananya   19  python     95         98  Bangalore
9         110   Meena   20   excel     90         94   Hyderbad

In [ ]:
#15
df[(df['marks'] > 80) & (df['attendace'] > 90)]

   student_id    name  age  course  marks  attendace       city
0         101   Aarav   20  python     85         92  Hyderabad
2         103   Rahul   19  python     92         96  Bangalore
6         107   Kiran   23   excel     81         91   Hyderbad
7         108  Ananya   19  python     95         98  Bangalore
9         110   Meena   20   excel     90         94   Hyderbad

In [ ]:
#Manpulating data
#crate the series
sales=pd.Series([5000,7000,None,9000,8000,10000,None],
index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
#Min value
print(sales.min())

5000.0

In [ ]:
#max value
print(sales.max())

10000.0

In [ ]:
#mean value
print(sales.mean())

7800.0

In [ ]:
#sum value
print(sales.sum())

39000.0

In [ ]:
#standard deviation
print(sales.std())

1923.5384061671346

In [ ]:
#varience value
print(sales.var())

3700000.0

In [ ]:
#type
print(sales.dtype)

float64

In [ ]:
#updating adding and replace(insertion)
sales['tuesday']=9500
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
tuesday       9500.0
dtype: float64

In [ ]:
#adding value
sales['january']=7800
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
tuesday       9500.0
january       7800.0
dtype: float64

In [ ]:
#drop or delete
sales=sales.drop("Tuesday")
print(sales)

Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
january       7800.0
dtype: float64

In [ ]:
#adding sales
print(sales+2000)
print(sales*2)

Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
january       9800.0
dtype: float64
Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
january      15600.0
dtype: float64

In [ ]:
s=pd.Series([1,2,3,4,5])
s1=pd.Series([101,102,103,104,105])
print(s)
print(s1)
c=pd.concat([s,s1])
d=pd.concat([s,s1],ignore_index=True)
e=pd.concat([s,s1],ignore_index=False)
print(d)
print(c)
print(e)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
0    101
1    102
2    103
3    104
4    105
dtype: int64

In [ ]:
data={
      'name':['Ravi','priya','Arun','Sneha','Kiran','Anjail','Vikram','Meena'],
      'age':[22,24,21,25,23,26,20,27],
      'city':['Hyderbad','Chennai','Bangalore',
              'Hyderbad','Mumbai','Chennai','Bangalore','Mumbai'],
      'salary':[30000,40000,28000,50000,35000,45000,25000,55000]}


df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       name  age       city  salary
101    Ravi   22   Hyderbad   30000
102   priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25   Hyderbad   50000
105   Kiran   23     Mumbai   35000
106  Anjail   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [ ]:
#aggregations
print(df['age'].sum())
print(df['salary'].sum)
print(df['age'].mean)
print(df['age'].max)

188
<bound method Series.sum of 101    30000
102    40000
103    28000
104    50000
105    35000
106    45000
107    25000
108    55000
Name: salary, dtype: int64>
<bound method Series.mean of 101    22
102    24
103    21
104    25
105    23
106    26
107    20
108    27
Name: age, dtype: int64>
<bound method Series.max of 101    22
102    24
103    21
104    25
105    23
106    26
107    20
108    27
Name: age, dtype: int64>

In [ ]:
df['Bonus']=df['salary']*0.10
print(df)

       name  age       city  salary   Bonus
101    Ravi   22   Hyderbad   30000  3000.0
102   priya   24    Chennai   40000  4000.0
103    Arun   21  Bangalore   28000  2800.0
104   Sneha   25   Hyderbad   50000  5000.0
105   Kiran   23     Mumbai   35000  3500.0
106  Anjail   26    Chennai   45000  4500.0
107  Vikram   20  Bangalore   25000  2500.0
108   Meena   27     Mumbai   55000  5500.0

In [ ]:
df['new salary']=df['salary']+df['Bonus']
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   22   Hyderbad   30000  3000.0     33000.0
102   priya   24    Chennai   40000  4000.0     44000.0
103    Arun   21  Bangalore   28000  2800.0     30800.0
104   Sneha   25   Hyderbad   50000  5000.0     55000.0
105   Kiran   23     Mumbai   35000  3500.0     38500.0
106  Anjail   26    Chennai   45000  4500.0     49500.0
107  Vikram   20  Bangalore   25000  2500.0     27500.0
108   Meena   27     Mumbai   55000  5500.0     60500.0

In [ ]:
df['age']=df['age']+1
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33000.0
102   priya   25    Chennai   40000  4000.0     44000.0
103    Arun   22  Bangalore   28000  2800.0     30800.0
104   Sneha   26   Hyderbad   50000  5000.0     55000.0
105   Kiran   24     Mumbai   35000  3500.0     38500.0
106  Anjail   27    Chennai   45000  4500.0     49500.0
107  Vikram   21  Bangalore   25000  2500.0     27500.0
108   Meena   28     Mumbai   55000  5500.0     60500.0

In [ ]:
df['new salary']=df['new salary']+500
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33500.0
102   priya   25    Chennai   40000  4000.0     44500.0
103    Arun   22  Bangalore   28000  2800.0     31300.0
104   Sneha   26   Hyderbad   50000  5000.0     55500.0
105   Kiran   24     Mumbai   35000  3500.0     39000.0
106  Anjail   27    Chennai   45000  4500.0     50000.0
107  Vikram   21  Bangalore   25000  2500.0     28000.0
108   Meena   28     Mumbai   55000  5500.0     61000.0

In [ ]:
df.loc[df['name'] == 'Priya','city'] = 'pune'
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33500.0
102   priya   25    Chennai   40000  4000.0     44500.0
103    Arun   22  Bangalore   28000  2800.0     31300.0
104   Sneha   26   Hyderbad   50000  5000.0     55500.0
105   Kiran   24     Mumbai   35000  3500.0     39000.0
106  Anjail   27    Chennai   45000  4500.0     50000.0
107  Vikram   21  Bangalore   25000  2500.0     28000.0
108   Meena   28     Mumbai   55000  5500.0     61000.0

In [ ]:
df.replace['city']

       name  age       city  salary   Bonus  new salary
101    Ravi   23  Hyderabad   30000  3000.0     33500.0
102   priya   25    Chennai   40000  4000.0     44500.0
103    Arun   22  Bangalore   28000  2800.0     31300.0
104   Sneha   26  Hyderabad   50000  5000.0     55500.0
105   Kiran   24     Mumbai   35000  3500.0     39000.0
106  Anjail   27    Chennai   45000  4500.0     50000.0
107  Vikram   21  Bangalore   25000  2500.0     28000.0
108   Meena   28     Mumbai   55000  5500.0     61000.0

In [ ]:
# Re-defining df with the correct columns first to ensure 'salary' exists
df = pd.DataFrame(data, index=[101,102,103,104,105,106,107,108])
df['Bonus'] = df['salary'] * 0.10
df['new salary'] = df['salary'] + df['Bonus']

# Now we can safely perform the calculation
df.loc[df['city'] == 'Mumbai', 'salary'] = df['salary'] * 1.05
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   22   Hyderbad   30000  3000.0     33000.0
102   priya   24    Chennai   40000  4000.0     44000.0
103    Arun   21  Bangalore   28000  2800.0     30800.0
104   Sneha   25   Hyderbad   50000  5000.0     55000.0
105   Kiran   23     Mumbai   36750  3500.0     38500.0
106  Anjail   26    Chennai   45000  4500.0     49500.0
107  Vikram   20  Bangalore   25000  2500.0     27500.0
108   Meena   27     Mumbai   57750  5500.0     60500.0

In [ ]:
df.loc[df['salary']<45000,'salary']=60000
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   22   Hyderbad   60000  3000.0     33000.0
102   priya   24    Chennai   60000  4000.0     44000.0
103    Arun   21  Bangalore   60000  2800.0     30800.0
104   Sneha   25   Hyderbad   50000  5000.0     55000.0
105   Kiran   23     Mumbai   60000  3500.0     38500.0
106  Anjail   26    Chennai   45000  4500.0     49500.0
107  Vikram   20  Bangalore   60000  2500.0     27500.0
108   Meena   27     Mumbai   57750  5500.0     60500.0

In [ ]:
df.drop('Bonus',axis=1,inplace=True)
print(df)

       name  age       city  salary  new salary
101    Ravi   22   Hyderbad   60000     33000.0
102   priya   24    Chennai   60000     44000.0
103    Arun   21  Bangalore   60000     30800.0
104   Sneha   25   Hyderbad   50000     55000.0
105   Kiran   23     Mumbai   60000     38500.0
106  Anjail   26    Chennai   45000     49500.0
107  Vikram   20  Bangalore   60000     27500.0
108   Meena   27     Mumbai   57750     60500.0

In [ ]:
df.drop(columns=['salary'],inplace=True)
print(df)

       name  age       city  new salary
101    Ravi   22   Hyderbad     33000.0
102   priya   24    Chennai     44000.0
103    Arun   21  Bangalore     30800.0
104   Sneha   25   Hyderbad     55000.0
105   Kiran   23     Mumbai     38500.0
106  Anjail   26    Chennai     49500.0
107  Vikram   20  Bangalore     27500.0
108   Meena   27     Mumbai     60500.0

In [ ]:
#read file csv
df = pd.read_csv("sales.csv")

In [ ]:
#read flie excel
df = pd.read_excel("sales_xlsx")

In [ ]:
#cleaning data
#detecting missing value (or) identify the missig value
# isnull() missing value
# isdrop() delete
# isnal() count or isnal() sum
# dropna() drop
# fillna() rename

In [ ]:
#cleaning data
import pandas as pd
sales=pd.Series([5000,7000,None,9000,8000,10000,None],
index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
sales.isna()

Monday       False
Tuesday      False
Wednesday     True
Thursday     False
Friday       False
Saturday     False
Sunday        True
dtype: bool

In [ ]:
sales.isna().sum()

np.int64(2)

In [ ]:

sales.dropna()

Monday       5000.0
Tuesday      7000.0
Thursday     9000.0
Friday       8000.0
Saturday    10000.0
dtype: float64

In [ ]:
sales.fillna(sales.mean())

Monday        5000.0
Tuesday       7000.0
Wednesday     7800.0
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday        7800.0
dtype: float64

In [ ]:
sales.fillna(0)

Monday        5000.0
Tuesday       7000.0
Wednesday        0.0
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           0.0
dtype: float64

In [ ]:
sales.fillna("need a data")

Monday            5000.0
Tuesday           7000.0
Wednesday    need a data
Thursday          9000.0
Friday            8000.0
Saturday         10000.0
Sunday       need a data
dtype: object

In [ ]:
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df_emp=pd.DataFrame(employees,index=I)
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp.isnull()

     EmpId   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp.isnull().sum()

EmpId         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp.isna().sum()

EmpId         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp.isna()

     EmpId   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp[['Salary', 'Department']].isna()

     Salary  Department
901   False       False
902   False       False
903    True       False
904   False        True

In [ ]:
df_emp.fillna({
    'Name' : 'unknown',
    'Department' : 0
})

     EmpId     Name Department   Salary
901    101     Asha      Sales  45000.0
902    102  unknown         IT  60000.0
903    103    Meena         HR      NaN
904    104      Sai          0  89000.0

In [ ]:
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp['Salary'].max()

89000.0

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].min())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].mean())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].sum())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].std())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].var())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df_emp=pd.DataFrame(employees,index=I)
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
#1
df_emp.head(2)

     EmpId  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [ ]:
df_emp.tail(2)

     EmpId   Name Department   Salary
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp[['Name','Salary']]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    Sai  89000.0

In [ ]:
df_emp[df_emp['EmpId'] == 103]

     EmpId   Name Department  Salary
903    103  Meena         HR     NaN

In [ ]:
df_emp[df_emp['Salary']>50000]

     EmpId  Name Department   Salary
902    102  None         IT  60000.0
904    104   Sai       None  89000.0

In [ ]:
df_emp[df_emp['Department']=='IT']

     EmpId  Name Department   Salary
902    102  None         IT  60000.0

In [ ]:
(df_emp['Name'].isna())|(df_emp['Department'].isna())

901    False
902     True
903    False
904     True
dtype: bool

In [ ]:
df_emp.isna().sum()

EmpId         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp.fillna({'Name':'unknown','Department':'Not assigned'})

     EmpId     Name    Department   Salary
901    101     Asha         Sales  45000.0
902    102  unknown            IT  60000.0
903    103    Meena            HR      NaN
904    104      Sai  Not assigned  89000.0

In [ ]:
df_emp['Bonus']=df_emp['Salary']*0.10
print(df_emp)

     EmpId   Name Department   Salary   Bonus
901    101   Asha      Sales  45000.0  4500.0
902    102   None         IT  60000.0  6000.0
903    103  Meena         HR      NaN     NaN
904    104    Sai       None  89000.0  8900.0

In [ ]:
df_emp.loc[df_emp['Name'] == 'Asha', 'Salary'] = 95000
print(df_emp)

     EmpId   Name Department   Salary   Bonus
901    101   Asha      Sales  95000.0  4500.0
902    102   None         IT  60000.0  6000.0
903    103  Meena         HR      NaN     NaN
904    104    Sai       None  89000.0  8900.0

In [11]:
import pandas as pd
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df_emp=pd.DataFrame(employees,index=I)
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [12]:
df_emp=df_emp.fillna({'Name': 'Sai','Department':'IT', 'Salary': 230000})
print(df_emp)

     EmpId   Name Department    Salary
901    101   Asha      Sales   45000.0
902    102    Sai         IT   60000.0
903    103  Meena         HR  230000.0
904    104    Sai         IT   89000.0

In [14]:
df_emp.groupby('Department')['Salary'].mean()

Department
HR       230000.0
IT        74500.0
Sales     45000.0
Name: Salary, dtype: float64

In [15]:
df_emp.groupby('Department')['Salary'].min()

Department
HR       230000.0
IT        60000.0
Sales     45000.0
Name: Salary, dtype: float64

In [16]:
df_emp.groupby('Department')['Salary'].max()

Department
HR       230000.0
IT        89000.0
Sales     45000.0
Name: Salary, dtype: float64

In [17]:
df_emp.groupby('Department')['Salary'].std()

Department
HR                NaN
IT       20506.096654
Sales             NaN
Name: Salary, dtype: float64

In [41]:
df_emp.groupby('Department')['Salary'].agg(['mean','min','max'])

                mean       min       max
Department
HR          230000.0  230000.0  230000.0
IT           74500.0   60000.0   89000.0
Sales        45000.0   45000.0   45000.0

In [21]:
import pandas as pd
data = {
    "name" : ["ravi","priya","Arun","sneha","kiran","Anjali","vikram","Meena"],
    "Age" : [22,24,21,25,23,26,20,27],
    "City" : ["Hyderabad","chennai","Banglore","Hydrerabad",
              "Mumbai","chennai","Banglore","Mumabi"],
    "Salary" : [30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index = [101,102,103,104,105,106,107,108])

In [22]:
print(df)

       name  Age        City  Salary
101    ravi   22   Hyderabad   30000
102   priya   24     chennai   40000
103    Arun   21    Banglore   28000
104   sneha   25  Hydrerabad   50000
105   kiran   23      Mumbai   35000
106  Anjali   26     chennai   45000
107  vikram   20    Banglore   25000
108   Meena   27      Mumabi   55000

In [25]:
print(df[['name','Salary']])

       name  Salary
101    ravi   30000
102   priya   40000
103    Arun   28000
104   sneha   50000
105   kiran   35000
106  Anjali   45000
107  vikram   25000
108   Meena   55000

In [29]:
df.loc[df['Age']>23]

       name  Age        City  Salary
102   priya   24     chennai   40000
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumabi   55000

In [30]:
df.loc[df['Salary']>40000]

       name  Age        City  Salary
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumabi   55000

In [32]:
df.loc[df['City']=='chennai']

       name  Age     City  Salary
102   priya   24  chennai   40000
106  Anjali   26  chennai   45000

In [34]:
df.loc[(df['Age'] > 22) & (df['Salary'] > 35000)]

       name  Age        City  Salary
102   priya   24     chennai   40000
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumabi   55000

In [37]:
df.loc[(df['City'] == 'Mumbai') | (df['City'] == 'Banglore')]

       name  Age      City  Salary
103    Arun   21  Banglore   28000
105   kiran   23    Mumbai   35000
107  vikram   20  Banglore   25000

In [39]:
df.loc[df['Salary']>35000,['name','Salary']]

       name  Salary
102   priya   40000
104   sneha   50000
106  Anjali   45000
108   Meena   55000

In [40]:
df.loc[102:104]

      name  Age        City  Salary
102  priya   24     chennai   40000
103   Arun   21    Banglore   28000
104  sneha   25  Hydrerabad   50000